app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//use Illuminate\Routing\Route;  isso daqui tava dando erro apos instalar o OAuth2, dava que os verbos
//não existiam


use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;
use LucaDegasperi\OAuth2Server\Facades\Authorizer;



Route::get('/', function () {
    return view('welcome');
});

Route::get('/test', function (){
    $repository = app()->make('CodeDelivery\Repositories\CategoryRepository');
    return $repository->all();
});

Route::group(['prefix' => 'admin','middleware' => 'auth.checkrole:admin', 'as'=>'admin.'], function (){

    Route::get('categories', ['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
    Route::get('categories/create',['as'=> 'categories.create' ,'uses' => 'CategoriesController@create']);
    Route::get('categories/edit/{id}',['as'=> 'categories.edit' ,'uses' => 'CategoriesController@edit']);
    Route::post('categories/store',['as'=> 'categories.store' ,'uses' => 'CategoriesController@store']);
    Route::post('categories/update/{id}',['as'=> 'categories.update' ,'uses' => 'CategoriesController@update']);


    Route::get('clients', ['as' => 'clients.index', 'uses' => 'ClientsController@index']);
    Route::get('clients/create',['as'=> 'clients.create' ,'uses' => 'ClientsController@create']);
    Route::get('clients/edit/{id}',['as'=> 'clients.edit' ,'uses' => 'ClientsController@edit']);
    Route::post('clients/store',['as'=> 'clients.store' ,'uses' => 'ClientsController@store']);
    Route::post('clients/update/{id}',['as'=> 'clients.update' ,'uses' => 'ClientsController@update']);


    Route::get('products', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
    Route::get('products/create',['as'=> 'products.create' ,'uses' => 'ProductsController@create']);
    Route::get('products/edit/{id}',['as'=> 'products.edit' ,'uses' => 'ProductsController@edit']);
    Route::post('products/store',['as'=> 'products.store' ,'uses' => 'ProductsController@store']);
    Route::post('products/update/{id}',['as'=> 'products.update' ,'uses' => 'ProductsController@update']);
    Route::get('products/destroy/{id}',['as'=> 'products.destroy' ,'uses' => 'ProductsController@destroy']);


    Route::get('orders',['as'=> 'orders.index' ,'uses' => 'OrdersController@index']);
    Route::get('orders/{id}',['as'=> 'orders.edit' ,'uses' => 'OrdersController@edit']);
    Route::post('orders/update/{id}',['as'=> 'orders.update' ,'uses' => 'OrdersController@update']);


    Route::get('cupoms',['as'=> 'cupoms.index' ,'uses' => 'CupomsController@index']);
    Route::get('cupoms/create',['as'=> 'cupoms.create' ,'uses' => 'CupomsController@create']);
    Route::post('cupoms/store',['as'=> 'cupoms.store' ,'uses' => 'CupomsController@store']);

});

Route::group(['prefix' => 'customer', 'middleware' => 'auth.checkrole:client', 'as' => 'customer.'], function (){

    Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
    Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
    Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);

});

Route::group(['middleware' => 'cors'], function (){

    Route::post('oauth/access_token', function() {
        return Response::json(Authorizer::issueAccessToken());
    });

    Route::group(['prefix' => 'api', 'middleware' => 'oauth', 'as' => 'api.'], function (){

        Route::group(['prefix' => 'client', 'middleware' => 'oauth.checkrole:client','as' => 'client.'], function (){

            Route::resource('order', 'Api\Client\ClientCheckoutController',
                ['except' => [ 'edit', 'destroy']]);
            //'create',isso é do except acima

            Route::get('products', 'Api\Client\ClientProductController@index'); //para listar os produtos que o cliente adicionou ao carrinho no app

//            Route::get('pedidos', function (){
//                return [
//                    'id' => 1,
//                    'client' => 'Manel soin',
//                    'total' => 10
//                ];
//            });
        });

        Route::group(['prefix' => 'deliveryman','middleware' => 'oauth.checkrole:deliveryman', 'as' => 'deliveryman.'], function (){

            Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController',
                ['except' => ['create', 'edit', 'destroy', 'store']]);

            Route::patch('order/{id}/update-status',
                ['uses' =>'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
                    'as' => 'orders.update_status'
                ]);

            Route::get('pedidos', function (){
                return [
                    'id' => 10,
                    'client' => 'Pure de natata soin',
                    'total' => 2000
                ];
            });
        });


    });
});

app/Models/Product.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Product extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'category_id',
        'name',
        'description',
        'price'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminCategoryRequest;

use CodeDelivery\Http\Requests\AdminProductRequest;
use CodeDelivery\Http\Requests\AdminProductRequestRequest;
use CodeDelivery\Repositories\CategoryRepository;
use CodeDelivery\Repositories\ProductRepository;
use Illuminate\Http\Request;

use CodeDelivery\Http\Requests;
use CodeDelivery\Http\Controllers\Controller;

class ProductsController extends Controller
{
    private $repository;
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;

    public function __construct(ProductRepository $repository, CategoryRepository $categoryRepository)
    {

        $this->repository = $repository;
        $this->categoryRepository = $categoryRepository;
    }

    public function index()
    {
        $products = $this->repository->paginate(5);
        //dd($products);
        return view('admin.products.index', compact('products'));
    }

    public function create()
    {
        $categories = $this->categoryRepository->lists(['name', 'id']);
        return view('admin.products.create', compact('categories'));
    }

    //public function store(AdminCategoryRequest $request)
    public function store(AdminProductRequest $request)
    {
        $data = $request->all(); //pega todos os dados que são enviados pelo request no caso  o nome da categoria que vem do fomulario
        $this->repository->create($data);    //manda pro repository salvar no db

        return redirect()->route('admin.products.index'); //redireciona pra pagina inicial
    }

    public function edit($id)
    {
        //o metodo edit recebe um id vindo da ulr
        $product = $this->repository->find($id); //ele pesquisa por esse id no repository

        $categories = $this->categoryRepository->lists(['name', 'id'])   ;

        return view('admin.products.edit', compact('product', 'categories')); //retorna essa requisição pra view

    }

    public function update(AdminProductRequest $request, $id)
    {
        $data = $request->all();
        $this->repository->update($data, $id);

        return redirect()->route('admin.products.index');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.products.index');
    }
}

resources/views/admin/products/_form.blade.php
<div class="form-group">
    {!! Form::label('Category', 'Categoria:') !!}

    {!! Form::select('category_id', $categories, null ,['class' => 'form-control']) !!}
</div>


<div class="form-group">
    {!! Form::label('Name', 'Nome:') !!}

    {!! Form::text('name', null ,['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Description', 'Descrição:') !!}

    {!! Form::textarea('description', null ,['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('Price', 'Preço:') !!}

    {!! Form::text('price', null ,['class' => 'form-control']) !!}
</div>

resources/views/admin/products/create.blade.php
@extends('app')


@section('content')

    <div class="container">
        <h3>Novo produto</h3>

    @include('errors._check')

    <!-- Passando esse array de rotas, da pra passar o action do form diretamente sem ter que
            definir um arquivo .php especifico para ser o action, ou seja, basta setar o nome de uma rota que ele ja vai
            usar a mesma-->

        {!! Form::open(['route' => 'admin.products.store']) !!}



        @include('admin.products._form')

        <div class="form-group">


            {!! Form::submit( 'Cadastrar produto', ['class' => 'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}

    </div>

@endsection

resources/views/admin/products/edit.blade.php
@extends('app')


@section('content')

    <div class="container">
        <h3>Editar produto {{ $product->name }}</h3>

            @include('errors._check')

            <!-- Passando esse array de rotas, da pra passar o action do form diretamente sem ter que
            definir um arquivo .php especifico para ser o action, ou seja, basta setar o nome de uma rota que ele ja vai
            usar a mesma-->

            {!! Form::model($product,  ['route' => ['admin.products.update', $product->id]]) !!}

               @include('admin.products._form')

                    <div class="form-group">


                    	{!! Form::submit( 'Salvar alterações', ['class' => 'btn btn-primary']) !!}
                    </div>

            {!! Form::close() !!}

    </div>

@endsection

resources/views/admin/products/index.blade.php
@extends('app')


@section('content')

    <div class="container">
        <h3>Produtos</h3>

        <a href="{{ route('admin.products.create') }}" class="btn btn-success">Novo Produto</a>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>Id</th>
                <th>Produto</th>
                <th>Categoria</th>
                <th>Preço</th>
                <th>Ação</th>
            </tr>
            </thead>

            <tbody>
            @foreach($products as $product)
            <tr>
                <td>{{ $product->id }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->category->name }}</td>
                <td>{{ $product->price }}</td>
                <td>
                    <a href="{{ route('admin.products.edit', ['id' => $product->id]) }}" class="btn btn-primary btn-sm">Editar</a>
                    <a href="{{ route('admin.products.destroy', ['id' => $product->id]) }}" class="btn btn-danger btn-sm">Excluir</a>
                </td>

            </tr>
            @endforeach
            </tbody>
        </table>

       <div class="text-center">
           {!! $products->render() !!}
       </div>

    </div>

@endsection